name: Create release

on:
  push:
    branches: [ main ]

env:
  os: ubuntu-22.04
  compiler: gcc-12

jobs:
  create_release:
    name: Creates a release with static binaries and uploads the library to the artifactory conan.dice-research.org
    runs-on: ubuntu-22.04
    steps:
      # cmake and conan to extract the version
      - name: Get minimum cmake version
        uses: lukka/get-cmake@v3.18.3
      - name: Install compiler
        id: install_cc
        uses: rlalik/setup-cpp-compiler@v1.1
        with:
          compiler: ${{ env.compiler }}
      - uses: rui314/setup-mold@v1
      - name: Install conan
        shell: bash
        run: |
          pip3 install conan
          conan profile new --detect default
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan profile update env.CXX="${CXX}" default
          conan profile update env.CC="${CC}" default
          conan remote add -f dice-group https://conan.dice-research.org/artifactory/api/conan/tentris
          conan remote add tentris-private https://conan.dice-research.org/artifactory/api/conan/tentris-private
          conan user -p "$CONAN_PW" -r tentris-private "$CONAN_USER"
        env:
          CONAN_PW: ${{ secrets.CONAN_PW }}
          CONAN_USER: ${{ secrets.CONAN_USER }}
          CC: ${{ steps.install_cc.outputs.cc }}
          CXX: ${{ steps.install_cc.outputs.cxx }}
      - name: Cache conan data
        id: cache-conan
        uses: actions/cache@v3
        with:
          path: ~/.conan/data
          key: ${{ env.os }}-${{ env.compiler }}-conan

      - name: Checkout
        uses: actions/checkout@v3

      # extract the version
      - name: Extract asset version
        id: extract_asset_version
        shell: bash
        run: |
          echo "asset_version=$(conan inspect . --raw version)" >> $GITHUB_ENV

      - name: Extract Tag
        uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: v${{ env.asset_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if tag exists already
        if: steps.checkTag.outputs.exists == 'true'
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            core.setFailed('There is already a tag for this version. Dump the version in CMakeLists.txt and try again.')

      - name: Build Dockerfile
        id: build-docker
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: tentris_server:latest
          cache-from: type=gha
          build-args: |
            "CONAN_USER=${{ secrets.CONAN_USER }}"
            "CONAN_PW=${{ secrets.CONAN_PW }}"

      - name: Build conan package (library) on Ubuntu
        shell: bash
        env:
          CC: ${{ steps.install_cc.outputs.cc }}
          CXX: ${{ steps.install_cc.outputs.cxx }}
        run: |
          (conan remove -f "$(conan inspect . --raw name)/$(conan inspect . --raw version)@" || true)
          conan create . "$(conan inspect . --raw name)/$(conan inspect . --raw version)@" --build missing -o boost:header_only=True -pr:b=default -pr:h=default

      - uses: shrink/actions-docker-extract@v1
        id: extract
        with:
          image: tentris_server:latest
          path: /.

      - name: zip assets
        shell: bash
        env:
          asset_version: ${{ env.asset_version }}
          asset_dir: ${{ steps.extract.outputs.destination }}
        run: zip "tentris_${asset_version}_clang14_libstdcxx11.zip" -j ${asset_dir}/*

      - name: Upload to artifactory
        shell: bash
        run: |
          conan upload "$(conan inspect . --raw name)/$(conan inspect . --raw version)@" --force --all -r tentris-private
          (conan remove -f "$(conan inspect . --raw name)/$(conan inspect . --raw version)@" || true)

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tentris_${{ env.asset_version }}_clang14_libstdcxx11.zip
          tag_name: "v${{ env.asset_version }}"
          draft: true
